using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.Extensions.Conventions: Conventions extension for Ninject")]
[assembly: AssemblyCompanyAttribute("Innovatian Software, LLC")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2009-2011 Innovatian Software, LLC and contributors")]
[assembly: AssemblyVersionAttribute("2.3.0.0")]
[assembly: AssemblyFileVersionAttribute("2.3.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

